njausteve/ex_pass

.formatter.exs
lib/structs/field_content.ex
lib/utils/validators.ex
mix.exs
mix.lock
test/structs/field_content_test.exs

Add FieldContent Struct with Validation and Update TypedStruct Dependency
This pull request adds the `typed_struct` dependency and introduces the `FieldContent` struct, which represents a field on a pass. The struct supports attributed values, including optional HTML markup for more dynamic content presentation. A `Validators` module is added to ensure that attributed values are properly validated, including checks for unsupported HTML tags. Tests are provided to verify struct creation and validation behaviors.
Tests have been added for:
- Creation of `FieldContent` structs with different types of attributed values (string, number, `DateTime`, and `Date`).
- Validation logic that raises `ArgumentError` for unsupported types or invalid HTML markup.
- **New Dependency**: The project now …

add field content structs

---

lib/structs/field_content.ex
lib/utils/converter.ex
lib/utils/validators.ex
test/structs/field_content_test.exs

Upgrade typedstruct dependency and add JSON encoding for FieldContent struct
This pull request includes the following updates:
- Migrated from the unmaintained `typed_struct` to the maintained `typedstruct` package to ensure future support and compatibility.
- Added JSON encoding functionality to the `FieldContent` struct in the `ExPass.Structs.FieldContent` module. The new encoder converts `FieldContent` struct data into camelCase keys and filters out `nil` values. This is critical for ensuring consistent interaction with external systems via APIs.
- Introduced a new attribute `change_message` in the `FieldContent` struct, which allows descriptive messages when field values change.
- Updated test cases for `FieldContent` to include validation of the `change_message` field.
- Added tests …

feat: add change_message attribute to field content

---

lib/structs/field_content.ex
lib/utils/validators.ex
test/structs/field_content_test.exs

Add `currency_code` field and validation to `FieldContent` struct
This PR introduces a `currency_code` field to the `FieldContent` struct, allowing the system to handle fields that represent monetary values more accurately. The field adheres to the ISO 4217 standard, ensuring correct and consistent use of currency codes.
Additionally, validation logic has been implemented to ensure only valid ISO 4217 codes are accepted. Unit tests have been added to cover the new field and its associated validation.
- Verified the correct handling of valid and invalid currency codes in the `FieldContent` struct.
- Added unit tests to check proper serialization and validation.
- Tested edge cases where the `currency_code` field is missing or contains invalid values.
- Affects all systems interacting with …

feat: Add currency_code field to FieldContent struct

---

lib/structs/field_content.ex
lib/utils/validators.ex
test/structs/field_content_test.exs

Add `data_detector_types` attribute to `FieldContent` struct for automatic data detection
This pull request introduces the `data_detector_types` attribute to the `FieldContent` struct. This attribute allows developers to specify a list of detectors that automatically convert data such as phone numbers, URLs, addresses, or calendar events into tappable links. The change aligns with the goal of making the field's content more interactive.
1. **New Attribute**:
- Adds `data_detector_types` to the `FieldContent` struct with support for the following types:
- "PKDataDetectorTypePhoneNumber"
- "PKDataDetectorTypeLink"
- "PKDataDetectorTypeAddress"
- "PKDataDetectorTypeCalendarEvent"
2. **Validator Updates**:
- A new validation function to verify that the data detectors are among the supported …

feat: Add data_detector_types attribute to FieldContent struct

---

lib/structs/field_content.ex
lib/utils/validators.ex
test/structs/field_content_test.exs

Add validation for `date_style` and support for data detectors in `FieldContent` struct
This pull request introduces two main features:
1. **Date Style Validation**: A new `date_style` field has been added to the `FieldContent` struct, allowing users to specify the format of displayed dates. The field supports several styles, including `PKDateStyleNone`, `PKDateStyleShort`, etc. Validation has been added to ensure that only valid styles or `nil` are used.
2. **Data Detectors**: The `data_detector_types` field now supports specifying a list of data detectors to automatically convert values into tappable links for phone numbers, URLs, addresses, and calendar events. By default, all detectors are applied, but an empty list can be specified to disable them.
- Unit tests were added for the …

add date style content field

---

lib/structs/field_content.ex
lib/utils/validators.ex
test/structs/field_content_test.exs

Add `ignores_time_zone` field to `FieldContent` struct with validation
This pull request introduces the `ignores_time_zone` field to the `FieldContent` struct. The `ignores_time_zone` field is a boolean value that determines whether the date and time displayed in the field should respect the current device's time zone (`false`) or the time zone associated with the provided date value (`true`). The default value is `false` if not specified.
- The field adds flexibility in controlling how time zones are handled in field displays.
- A validation function ensures that only valid boolean values are accepted.
- Unit tests were added to validate the behavior of the `ignores_time_zone` field.
- Verified that the field accepts valid boolean values (`true`, `false`).
- Tested the default behavior …

feat: Add validation for ignores_time_zone field in FieldContent struct

---

lib/structs/field_content.ex
lib/utils/validators.ex
test/structs/field_content_test.exs

Add `is_relative` field to `FieldContent` struct for relative date display
This pull request adds a new `is_relative` field to the `FieldContent` struct. The `is_relative` field is a boolean value that controls whether dates are displayed as absolute dates (e.g., "April 1, 2023") or as relative dates (e.g., "2 days ago"). The default value is `false`, meaning dates are displayed as absolute unless explicitly set to `true`.
- This feature enhances flexibility by allowing dates to be presented in a way that provides better context to users.
- Added unit tests to validate the `is_relative` field, including scenarios where it is set to `true`, `false`, or not provided.
- Verified that the validation function correctly rejects non-boolean values.
- The `FieldContent` struct now supports …

feat: Add is_relative field to FieldContent struct

---

lib/structs/field_content.ex
lib/utils/validators.ex
test/structs/field_content_test.exs

Enhance FieldContent Struct with `is_relative` Date Handling and Required `key` Field
This PR introduces two main changes to the `FieldContent` struct:
1. **`is_relative` field**: A Boolean value allowing for the display of relative or absolute dates.
2. **`key` field**: A mandatory unique string that identifies each `FieldContent` instance.
These changes extend the flexibility of date representations and improve the system’s data integrity by ensuring that each field has a unique identifier.
- New test cases for the `is_relative` field have been added to ensure proper handling of relative dates.
- Validation logic for the `key` field is tested to confirm it enforces a non-empty string value.
- The new `is_relative` field introduces more flexibility in date formatting.
- The `key` field …

feat: Add key required key field in PassFieldContent

---

lib/structs/field_content.ex
lib/utils/validators.ex
test/structs/field_content_test.exs

Add `label` field to `PassFieldContent`
This PR adds a new optional `label` field to the `PassFieldContent` struct. The `label` field allows the specification of text for a field label, enhancing the customization of `PassFieldContent` display.
Key changes:
1. **Addition of `label` field**: An optional string field to display text as a label.
2. **Validation of `label`**: Ensures that the `label` is either a valid string or nil.
3. **Tests**: Test cases have been added to ensure the correct functionality of the new `label` field, including handling of valid strings, nil, and trimming of whitespace.
- Added unit tests to verify that the `label` field functions correctly:
- Valid label strings are properly encoded.
- Nil values are handled as expected.
- Non-string labels trigger validation …

feat: Add label to PassFieldContent

---

lib/structs/field_content.ex
lib/utils/validators.ex
test/structs/field_content_test.exs

Add number_style support to FieldContent and refactor validation error handling
This pull request introduces a new `number_style` field to the `FieldContent` struct. The `number_style` field supports various number formats, such as `"PKNumberStyleDecimal"`, `"PKNumberStylePercent"`, `"PKNumberStyleScientific"`, and `"PKNumberStyleSpellOut"`, providing flexibility for numerical display.
Additionally, the validation logic in `Validators` has been updated to handle this new field, ensuring that only valid number formats are allowed. Error handling was refactored to streamline error messages, improving code readability and maintainability.
- Added unit tests for the `number_style` field in `FieldContent`.
- Verified error handling for invalid `number_style` inputs.
- Confirmed backward …

add number style pass field content field

---

lib/structs/field_content.ex
lib/utils/validators.ex
mix.exs
test/structs/field_content_test.exs

Add optional `text_alignment` field to `FieldContent` struct with validation
This PR adds a new optional `text_alignment` field to the `FieldContent` struct, allowing the text in a field to be aligned to the left, center, right, or natural alignment. The supported values are "PKTextAlignmentLeft", "PKTextAlignmentCenter", "PKTextAlignmentRight", and "PKTextAlignmentNatural". Validation has been implemented to ensure that only these values are accepted. Tests have been updated to verify correct functionality.
New tests have been added to ensure that the `text_alignment` field accepts valid values and rejects invalid ones. Behavior when the field is omitted or set to `nil` has also been tested to ensure correct default handling.
This change is backward-compatible since the `text_alignment` …

feat: Add validation for text alignment field in FieldContent struct

---

lib/structs/barcodes.ex
lib/utils/validators.ex
test/structs/barcodes_test.exs

Add Barcode Format Validation to Barcodes Struct
This pull request introduces a feature that adds barcode format validation to the `Barcodes` struct in the `ExPass` repository. The update includes:
1. **Barcode Format Field**: A new `:format` field has been added to the `Barcodes` struct, which is now mandatory. This field allows for the specification of barcode formats, including `PKBarcodeFormatQR`, `PKBarcodeFormatPDF417`, `PKBarcodeFormatAztec`, and `PKBarcodeFormatCode128`. It is worth noting that `PKBarcodeFormatCode128` is not supported for watchOS.
2. **Validation**: A new validator, `validate_barcode_format/1`, has been implemented to ensure that only valid barcode formats are accepted. This function checks if the provided barcode format matches one of the supported formats.
3. …

feat: Add barcode format validation to Barcodes struct

---

lib/structs/barcodes.ex
test/structs/barcodes_test.exs

This pull request introduces a new feature to the `Barcodes` struct in the `ExPass` repository. The following changes have been made:
1. **New `message` Field**: A new required field called `message` has been added to the `Barcodes` struct. This field represents the payload or message that will be displayed as a barcode. It must be a non-empty string, and its presence is now enforced when creating a `Barcodes` struct.
2. **Validation**: The `message` field is validated using a new rule that ensures the field is present and contains a valid string. It is now required for struct creation.
3. **Updates to Tests**: The test suite has been updated to cover cases related to the new `message` field. Tests now ensure that the field is enforced, that valid values work correctly, and that invalid …

feat: Add message field to Barcodes struct

---

lib/structs/barcodes.ex
lib/utils/validators.ex
test/structs/barcodes_test.exs

This pull request introduces support for validating the encoding of the `message` field within the `Barcodes` struct. Key changes include:
1. **New `message_encoding` Field**: 
- A new field `message_encoding` has been added to the `Barcodes` struct. It allows specifying the character encoding used for the `message`, which is crucial for converting the text into the data rendered as a barcode.
- The `message_encoding` field must be a valid IANA character set, with supported formats including `US-ASCII`, `ISO-8859-1` to `ISO-8859-10`, `Shift_JIS`, `EUC-JP`, `ISO-2022-KR`, and more.
2. **Validation**: 
- A validation function, `validate_message_encoding/1`, has been added to ensure that the provided `message_encoding` is valid. The system will reject unsupported or missing encodings with …

feat: Add support for validating message encoding in Barcodes struct

---

lib/structs/beacons.ex
lib/utils/validators.ex
test/structs/beacons_test.exs

This pull request introduces the `ExPass.Structs.Beacons` module, which adds support for representing Bluetooth Low Energy (BLE) beacons in the system. The main feature is the new `:major` field, a 16-bit unsigned integer representing the beacon’s major identifier. The module provides the `Beacons.new/1` function for creating a new beacon struct and includes validation for the `:major` field via the `validate_optional_16bit_unsigned_integer/1` function.
The `Beacons` struct implements the `Jason.Encoder` protocol, allowing it to be serialized into JSON format. Additionally, test cases for struct creation, validation, and encoding have been added to ensure correctness.
- New tests have been added to validate the `Beacons` struct, including:
- Validation of valid and invalid `:major` field …

feat: Add ExPass.Structs.Beacons module for representing Bluetooth Low Energy beacons

---

lib/structs/beacons.ex
lib/utils/validators.ex
test/structs/beacons_test.exs

This pull request enhances the `ExPass.Structs.Beacons` module by adding support for a new `:minor` field, alongside the existing `:major` field. Both fields represent 16-bit unsigned integers used to identify Bluetooth Low Energy (BLE) beacons, allowing for more precise identification. Validation logic for these fields has been improved, ensuring clear error messages when invalid values are encountered. Additionally, JSON encoding has been updated to camelize field names and omit null values, ensuring clean serialization.
- New tests were added for the `:minor` field, covering valid and invalid values.
- Tests for the updated validation logic ensure that error messages correctly identify problematic fields.
- JSON encoding tests verify that only non-null fields are included in the …

feat: Update ExPass.Structs.Beacons module to handle 16-bit unsigned integers with underscores

---

lib/structs/beacons.ex
lib/utils/validators.ex
test/structs/beacons_test.exs

This pull request adds a new `:proximityUUID` field to the `ExPass.Structs.Beacons` module, which is now required for all beacon structs. The `:proximityUUID` field uniquely identifies Bluetooth Low Energy (BLE) beacons. Additionally, the `major` and `minor` fields remain supported, but they are optional. A new validation function, `validate_uuid/1`, ensures that the `proximityUUID` field contains a valid UUID string.
The existing JSON encoding logic has also been updated to include the `proximityUUID` field and to properly camelize field names. This change enhances the module’s ability to handle BLE beacons more robustly, improving location-based pass functionality.
- Tests for valid and invalid `proximityUUID` values have been added.
- Additional tests ensure the correct behavior of the …

feat: Add validation for proximityUUID in ExPass.Structs.Beacons module

---

lib/structs/beacons.ex
lib/utils/validators.ex
test/structs/beacons_test.exs

This PR introduces the following changes:
- Adds new fields `minor`, `proximity_UUID` (required), and `relevant_text` (optional) to the `ExPass.Structs.Beacons` module.
- Updates validation logic to ensure `minor` is a 16-bit unsigned integer and `proximity_UUID` is a valid UUID.
- Updates JSON encoding for the new fields, ensuring camel-cased field names are used.
- Updates and adds new tests to cover the validation and struct creation process.
- Unit tests have been added to ensure proper validation and encoding of the `minor`, `proximity_UUID`, and `relevant_text` fields.
- Edge cases such as invalid UUID strings, negative integers, and exceeding integer limits are covered.
- JSON encoding tests ensure correct camel-casing and handling of optional fields when they are `nil`.
- These …

Add relevant_text fields to Beacons struct with validation

---

lib/structs/locations.ex
lib/utils/validators.ex
test/structs/field_content_test.exs
test/structs/locations_test.exs

Add `Locations` Struct with Altitude Field and Validation Logic
This PR introduces a new `Locations` struct to the ExPass system to represent a geographic location. The struct includes an `altitude` field, which is validated to ensure that it is either a float or nil. The change includes a corresponding validation function and a set of tests to ensure that the `altitude` field behaves correctly under different scenarios.
A validator function `validate_optional_float/2` has been added to ensure that only floats are accepted for the altitude value.
Tests have been added for the new `Locations` struct to ensure the following:
- The struct can be created with default values.
- Valid floats (including negative and zero values) are accepted for the altitude field.
- Invalid values (such as …

feat: Add Locations struct with altitude field validation

---

README.md
lib/structs/locations.ex
lib/utils/validators.ex
test/structs/locations_test.exs

Add Latitude Validation to Locations Struct and Enhance Altitude Handling
This pull request adds a new `latitude` field to the `Locations` struct in the ExPass system, making it a required field. The `latitude` must be a float between -90 and 90 degrees. The existing `altitude` field remains optional but is validated to ensure it is a float if provided.
The changes include validation functions to enforce these constraints, with appropriate error messages for invalid inputs. Unit tests have been added to verify the correct behavior of both fields.
Unit tests have been added to cover the following scenarios:
- Valid latitude and altitude values are accepted.
- Latitude values outside the valid range of -90 to 90 degrees raise appropriate errors.
- Non-float values for both latitude and …

feat: Add latitude field validation to Locations struct

---

README.md
lib/structs/locations.ex
lib/utils/validators.ex
test/structs/locations_test.exs

Add Longitude Validation to Locations Struct and Update Geographic Constraints
This pull request introduces a new `longitude` field to the `Locations` struct in the ExPass system. Longitude is a required field and must be a float between -180 and 180 degrees. The existing `latitude` field is still validated between -90 and 90 degrees. 
Validation functions for both latitude and longitude have been added, ensuring that only valid geographic coordinates are accepted.
The README has been updated to reflect the completion of the longitude field in the project’s progress.
Unit tests have been updated to verify the following:
- Valid longitude values (between -180 and 180) are accepted.
- Invalid longitude values (outside the range or non-float values) raise appropriate errors.
- The …

91 add longitude field for locations

---

README.md
lib/structs/beacons.ex
lib/structs/locations.ex
test/structs/locations_test.exs

Add Optional `relevant_text` Field to Locations Struct for Contextual Messaging
This pull request introduces a new optional field, `relevant_text`, to the `Locations` struct in the ExPass system. This field allows a descriptive message to be displayed when the pass is relevant, providing users with context such as information about a nearby store.
Validation ensures that `relevant_text`, if provided, is a valid string, and any extraneous whitespace is trimmed. The corresponding tests ensure that the field is correctly validated, trimmed, and serialized.
New tests have been added to verify:
- Correct acceptance of valid strings for the `relevant_text` field.
- Trimming of leading and trailing whitespace from the field.
- Rejection of non-string values with appropriate error messages.
- …

92 add relevanttext field for locations

---

README.md
lib/structs/semantic_tags/seat.ex
test/structs/semantic_tags/seat_test.exs

Add optional `seat_type` field to Seat Struct for Semantic Tags.
This pull request introduces a new `Seat` struct within the `ExPass` library to represent the identification of a seat for a transit journey or an event. The struct includes a `seat_type` field, which is optional and can be used to specify the type of seat, such as "Reserved seating". Additionally, tests have been added to ensure the correct functionality of the `Seat` struct, including validation and JSON encoding.
The following tests have been added to verify the functionality of the `Seat` struct:
- Creation of a valid `Seat` struct with and without `seat_type`.
- Trimming of whitespace from `seat_type`.
- Validation to ensure `seat_type` is a string.
- Handling of empty string for `seat_type`.
This change adds a new …

114 add seat_type field for seat

---

lib/structs/semantic_tags/seat.ex

Add Base Module Usage and Remove Unwanted Code in Seat Struct
This pull request refactors the `Seat` struct in the `lib/structs/semantic_tags/seat.ex` file. The changes include:
- Adding the `ExPass.Structs.Base` module usage to the `Seat` struct.
- Removing the `validate` function and the `Jason.Encoder` implementation, which were not being used.
These changes help streamline the code by removing unnecessary parts and ensuring that the `Seat` struct is consistent with other structs that use the `ExPass.Structs.Base` module.
The changes were tested by running the existing test suite to ensure that no functionality was broken by the removal of the unused code. No new tests were added as the changes do not introduce new functionality.
The refactoring should have minimal impact on the …

refactor: :recycle: Refactor Seat module to use base struct

---

lib/structs/nfc.ex
test/structs/nfc_test.exs

This PR adds support for the NFC (Near Field Communication) functionality in Apple Wallet passes by implementing the `requires_authentication` field. This field allows passes to require user authentication for each use of the NFC pass, enhancing security for sensitive NFC transactions.
The implementation follows Apple's documentation for the Pass.NFC object, specifically focusing on the `requiresAuthentication` property. As specified in the requirements, only this field has been implemented at this time, with other NFC fields to be added in future PRs.
Key changes:
- Created a new `ExPass.Structs.NFC` module with the `requires_authentication` field
- Implemented proper validation for boolean values
- Added comprehensive tests with 100% code coverage
- Ensured proper JSON encoding with …

95 add requiresauthentication field for nfc

---

lib/structs/nfc.ex
lib/utils/validators.ex
test/structs/nfc_test.exs

You're right. Let me reformat the PR description to match the structure of the template exactly:
Add NFC support with message and requiresAuthentication fields
This PR adds support for the NFC (Near Field Communication) functionality in Apple Wallet passes by implementing the `message` and `requires_authentication` fields. These fields allow passes to transmit NFC payloads to Apple Pay terminals and optionally require user authentication for each use of the NFC pass.
The implementation follows Apple's documentation for the Pass.NFC object, focusing on:
1. The required `message` field (payload transmitted to Apple Pay terminals, max 64 bytes)
2. The optional `requires_authentication` field (boolean that determines if authentication is required)
Key changes:
- Created a new …

feat: add message field to NFC struct with validation

---

.gitignore
lib/structs/nfc.ex
lib/utils/public_key.ex
mix.exs
test/structs/nfc_test.exs
test/utils/public_key_test.exs

This PR adds support for the encryption public key field in NFC passes, which is required by the Value Added Services protocol. Key changes include:
1. Added a new required `encryption_public_key` field to the `NFC` struct
2. Created a new validation module `ExPass.Utils.PublicKey` to ensure the key is a valid Base64-encoded X.509 SubjectPublicKeyInfo structure containing an ECDH public key for group P256
3. Added `:public_key` to extra applications in `mix.exs` to support the cryptographic validation
4. Updated all tests to include the new required field and added tests specifically for the new field validation
These changes are necessary to comply with Apple's requirements for NFC passes that use the Value Added Services protocol, which requires a valid ECDH P256 public key.
All …

93 add encryptionpublickey field for nfc

---

README.md
lib/structs/semantic_tags/seat.ex
test/structs/semantic_tags/seat_test.exs

This PR introduces a new optional field `seat_description` to the `Seat` struct within the `ExPass.Structs.SemanticTags.Seat` module. This field allows users to provide a descriptive text for a seat, such as "A flat bed seat" or "Push back seat".
- Adding the `seat_description` field to the `Seat` struct.
- Updating the `new/1` function to handle the new field with appropriate validation.
- Updating documentation and doctests to reflect the new field.
- Adding comprehensive tests to ensure correct behavior, including trimming whitespace, handling empty strings, and validating input types.
This addresses issue #109.
Added unit tests covering:
- Creation of `Seat` struct with and without `seat_description`.
- JSON encoding verification.
- Whitespace trimming functionality.
- Validation of …

[109] Add seat description field for Seat struct

---

README.md
lib/structs/semantic_tags/seat.ex
test/structs/semantic_tags/seat_test.exs

[Provide a succinct and descriptive title for the pull request, e.g., "Improve caching mechanism for API calls"]
This PR expands the `Seat` struct in the `ExPass.Structs.SemanticTags.Seat` module by adding several optional fields:
- `seat_identifier`: A unique identifier for the seat (e.g., "Aisle 12, Row 3, Seat 5").
- `seat_number`: The seat number (e.g., "3A").
- `seat_row`: The row of the seat (e.g., "3").
- `seat_section`: The section of the seat (e.g., "Aisle 12").
- Updating the struct definition to include the new fields.
- Extending the `new/1` function to handle these fields with proper validation.
- Updating documentation and doctests to reflect the new fields.
- Adding comprehensive tests for each new field, covering creation, validation, whitespace trimming, JSON encoding, …

[110][111][112][113] Add additional seat-related fields to Seat struct
